#ifndef CONSTANTS_H
#define CONSTANTS_H
#define TRUE 1

char *MISSING_FILE_PARAM_MSG;
char *LIST_CREATION_SUCCESS;
char *USER_OPTIONS;
char *OPTION_PROMPT;
char *INVALID_USER_INPUT_MSG;
char *GOODBYE_MSG;

#endif